apiVersion: apps/v1
kind: Deployment
metadata:
  name: highload
spec:
  selector:
    matchLabels:
      run: highload
  replicas: 2
  template:
    metadata:
      labels:
        run: highload
    spec:
      containers:
      - name: highload
        image: antonshcherbyna/highload:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /livetest
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /livetest
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
